framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~

    #esi: true
    #fragments: true
    php_errors:
        log: true

    cache:
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        prefix_seed: DDBCover

        # Redis
        system: cache.adapter.redis
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_CACHE_DSN)%'

        pools:
            # Creates a "no.hits.cache" service
            no.hits.cache:
                adapter: cache.adapter.redis
                # Default expire set to one day
                default_lifetime: '%env(int:APP_NO_HITS_CACHE_TTL)%'

parameters:
    env(CLOUDINARY_CONFIG_FILE): '%kernel.project_dir%/config/cloudinary.yml'
