---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cover-service
  name: cover-service-jobs-config
data:
  PHP_MEMORY_LIMIT: "256M"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cover-service
  name: cover-service-jobs
spec:
  selector:
    matchLabels:
      app: cover-service-jobs
  template:
    metadata:
      labels:
        app: cover-service-jobs
        tier: frontend
    spec:
      imagePullSecrets:
        - name: github-registry
      containers:
      - name: coverservice
        image: docker.pkg.github.com/danskernesdigitalebibliotek/ddb-cover-service/cover-service-jobs
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "600m"
        env:
          - name: APP_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: cover-service-secret
                key: APP_DB_USERNAME
          - name: APP_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cover-service-secret
                key: APP_DB_PASSWORD
          - name: APP_OPENPLATFORM_ID
            valueFrom:
              secretKeyRef:
                name: cover-service-secret
                key: APP_OPENPLATFORM_ID
          - name: APP_OPENPLATFORM_SECRET
            valueFrom:
              secretKeyRef:
                name: cover-service-secret
                key: APP_OPENPLATFORM_SECRET
          - name: APP_CLOUDINARY_ID
            valueFrom:
              secretKeyRef:
                name: cover-service-secret
                key: APP_CLOUDINARY_ID
          - name: APP_CLOUDINARY_SECRET
            valueFrom:
              secretKeyRef:
                name: cover-service-secret
                key: APP_CLOUDINARY_SECRET
          - name: APP_SECRET
            valueFrom:
              secretKeyRef:
                name: cover-service-secret
                key: APP_SECRET
          - name: APP_ELASTIC_USERNAME
            valueFrom:
              secretKeyRef:
                name: cover-service-secret
                key: APP_ELASTIC_USERNAME
          - name: APP_ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cover-service-secret
                key: APP_ELASTIC_PASSWORD
        envFrom:
          - configMapRef:
              name: cover-service-config
          - configMapRef:
              name: cover-service-jobs-config
